// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  type PublicPath =
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icons/icon128.png"
    | "/icons/icon16.png"
    | "/icons/icon48.png"
    | "/options.html"
    | "/popup.html"
  export interface WxtRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
  }
}
