name: Build Extension Releases

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Chrome
        run: npm run build:chrome

      - name: Build Firefox
        run: npm run build:firefox

      - name: Create zips
        run: npm run zip

      - name: Rename Chrome zip with version tag
        run: mv dist/nas-download-helper-chrome.zip dist/nas-download-helper-chrome-${{ github.event.release.tag_name }}.zip

      - name: Rename Firefox zip with version tag
        run: mv dist/nas-download-helper-firefox.zip dist/nas-download-helper-firefox-${{ github.event.release.tag_name }}.zip

      - name: Upload Chrome zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/nas-download-helper-chrome-${{ github.event.release.tag_name }}.zip
          asset_name: nas-download-helper-chrome-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip

      - name: Upload Firefox zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/nas-download-helper-firefox-${{ github.event.release.tag_name }}.zip
          asset_name: nas-download-helper-firefox-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
